apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sage-es-data
  labels:
    app.kubernetes.io/name: sage-es
    app.kubernetes.io/part-of: sage
spec:
  accessModes:
    - ReadWriteOnce
  ${PVC_STORAGE_CLASS}
  resources:
    requests:
      storage: 30Gi
