apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sage-server-logs
  labels:
    app.kubernetes.io/name: sage-server
    app.kubernetes.io/part-of: sage
spec:
  accessModes:
    - ReadWriteOnce
  ${PVC_STORAGE_CLASS}
  resources:
    requests:
      storage: 10Gi
