apiVersion: v1
kind: Service
metadata:
  name: sage-es
  labels:
    app.kubernetes.io/name: sage-es
    app.kubernetes.io/part-of: sage
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: sage-es
  ports:
    - name: http
      port: 9200
      targetPort: http
