apiVersion: v1
kind: Service
metadata:
  name: sage-jaeger
  labels:
    app.kubernetes.io/name: sage-jaeger
    app.kubernetes.io/part-of: sage
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: sage-jaeger
  ports:
    - name: otlp-grpc
      port: 4317
      targetPort: otlp-grpc
    - name: otlp-http
      port: 4318
      targetPort: otlp-http
    - name: query
      port: 16686
      targetPort: query
    - name: health
      port: 13133
      targetPort: health
