apiVersion: v1
kind: Service
metadata:
  name: sage-mysql
  labels:
    app.kubernetes.io/name: sage-mysql
    app.kubernetes.io/part-of: sage
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: sage-mysql
  ports:
    - name: mysql
      port: 3306
      targetPort: mysql
