apiVersion: v1
kind: Service
metadata:
  name: sage-web
  labels:
    app.kubernetes.io/name: sage-web
    app.kubernetes.io/part-of: sage
spec:
  type: ${SAGE_WEB_SERVICE_TYPE}
  selector:
    app.kubernetes.io/name: sage-web
  ports:
    - name: http
      port: 80
      targetPort: http
      ${SAGE_WEB_NODE_PORT_LINE}
